// Copyright (c) 2021 - 2023  Intel Corporation
//
// SPDX-License-Identifier: BSD-2-Clause-Patent

// Auto-generated by `td-layout-config`, do not edit manually.

/*
Mem Layout Example
+----------------------------------------+ <- 0x80000000
|               EVENT_LOG                |   (0x100000) 1 MB
+----------------------------------------+ <- 0x7FF00000
|            PAYLOAD_MAILBOX             |   (0x2000) 8 KB
+----------------------------------------+ <- 0x7FEFE000
|           PAYLOAD_PAGE_TABLE           |   (0x20000) 128 KB
+----------------------------------------+ <- 0x7FEDE000
|                  ACPI                  |   (0x100000) 1 MB
+----------------------------------------+ <- 0x7FDDE000
|                  FREE                  |   (0x7757D000) 1.86 GB
+----------------------------------------+ <- 0x8861000
|                PAYLOAD                 |   (0x8000000) 128 MB
+----------------------------------------+ <- 0x861000
|             PAYLOAD_PARAM              |   (0x1000) 4 KB
+----------------------------------------+ <- 0x860000
|           LAZY_ACCEPT_BITMAP           |   (0x40000) 256 KB
+----------------------------------------+ <- 0x820000
|                 TD_HOB                 |   (0x20000) 128 KB
+----------------------------------------+ <- 0x800000
|               BOOTLOADER               |   (0x800000) 8 MB
+----------------------------------------+ <- 0x0
Total memory length: 0x80000000 (2 GB)
Total usage: 0x8A83000 (138.51 MB)
*/

// Runtime Layout Configuration
pub const BOOTLOADER_BASE: usize = 0x0;
pub const BOOTLOADER_SIZE: usize = 0x800000; // 8 MB
pub const TD_HOB_BASE: usize = 0x800000;
pub const TD_HOB_SIZE: usize = 0x20000; // 128 KB
pub const LAZY_ACCEPT_BITMAP_BASE: usize = 0x820000;
pub const LAZY_ACCEPT_BITMAP_SIZE: usize = 0x40000; // 256 KB
pub const PAYLOAD_PARAM_BASE: usize = 0x860000;
pub const PAYLOAD_PARAM_SIZE: usize = 0x1000; // 4 KB
pub const PAYLOAD_BASE: usize = 0x861000;
pub const PAYLOAD_SIZE: usize = 0x8000000; // 128 MB
pub const ACPI_SIZE: usize = 0x100000; // 1 MB
pub const PAYLOAD_PAGE_TABLE_SIZE: usize = 0x20000; // 128 KB
pub const PAYLOAD_MAILBOX_SIZE: usize = 0x2000; // 8 KB
pub const EVENT_LOG_SIZE: usize = 0x100000; // 1 MB

pub const MEMORY_LAYOUT_CONFIG: &[(&'static str, usize, &'static str)] = &[
    // (name of memory region, region size, region type)
    ("Bootloader", 0x800000, "Memory"),
    ("TdHob", 0x20000, "Memory"),
    ("LazyAcceptBitmap", 0x40000, "Memory"),
    ("PayloadParam", 0x1000, "Memory"),
    ("Payload", 0x8000000, "Memory"),
    ("Acpi", 0x100000, "Acpi"),
    ("PayloadPageTable", 0x20000, "Reserved"),
    ("PayloadMailbox", 0x2000, "Nvs"),
    ("EventLog", 0x100000, "Nvs"),
];

// Total Memory Usage
pub const TOTAL_USAGE: usize = 0x8A83000; // 138.51 MB
